#!/bin/sh

set -e

add=false

while getopts u:p:a o; do
  case "$o" in
    u)  user="${OPTARG}";;
    p)  password="${OPTARG}";;
    a)  add=true;;
    [?])  echo "Usage: $0 [-u user] [-p password] [-a] rs_name master_node secondary_node ..." >&2
          exit 1;;
  esac
done
shift $(( $OPTIND - 1 ))

rs_name=$1
master_node=$2
shift 2

mongo -u $user -p $password --eval "printjson(rs.initiate({'_id': '${rs_name}', 'members': [{ '_id': 0, 'host': '${master_node}:27017'}]}))" admin
if $add; then
  for secondary_node in $*; do
    mongo -u $user -p $password --eval "printjson(rs.add('${secondary_node}:27017'))" admin
  done
fi
