#!/bin/sh

set -e

backup_dir=/var/backups/mongodb
restore_files=true

user=''
password=''

default_backup_files=""

while getopts d:u:p: o; do
  case "$o" in
    d)  backup_dir="${OPTARG}";;
    u)  user="${OPTARG}";;
    p)  password="${OPTARG}";;
    [?])  print >&2 "Usage: $0 [-i] [-d backup_dir] {files_to_recover}"
          exit 1;;
  esac
done
shift $(( $OPTIND - 1 ))

backup_files=$*

if [ "X$backup_files" = "X" ]; then
  backup_files=$default_backup_files
fi

if [ -z $user ]; then
  RESTORE_COMMAND="mongorestore"
else
  RESTORE_COMMAND="mongorestore -u $user -p $password"
fi

for backup_file in $backup_files; do
  echo "Restoring $backup_file from $backup_dir"
  $RESTORE_COMMAND "${backup_dir}/${backup_file}"
done
